version: '3.7'

networks:
  default:
    external:
      name: skeleton

services:
  migration:
    build:
      context: .
      dockerfile: ./tools/sql_migration/Dockerfile
    environment:
      DB_NAME: ${DB_NAME:-db}
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-55432}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
    restart: "no"
    volumes:
      - ./migrations:/opt/migrations:rw

  skdb:
    image: postgres:latest
    restart: always
    ports:
      - "55432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
      POSTGRES_USER: root

  skeleton:
    depends_on:
      - skdb
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "55782:80"

volumes:
  postgres:
